---
title: "Reexamine the outcome of the 2019 Canadian General election: Conservative Party of Canada would have win the election with a full voter turnout"
author: "boyu sheng"
date: "2020/12/9"
output: pdf_document
---

# Abstract 

On October 21st 2019, the result of the 43th Canadian General Election came out with the victory of Liberal Party and Justin Trudeau, the leader of the Liberal Party has been reelected as the Prime Minister. However, the Liberal Party only formed a minority government as they only led the Conservative Party by 36 seats in the Parliament and the seats Liberal Party obtained in the election did not achieve 50% of the total seats. With the relatively low voter turnout in the election of 67%, there was a potential for the Conservatives to overturn the result of this election. Hence in the research, I use the Multilevel Regression with Post-stratification Model (MRP) to simulate the outcome of the 2019 election with a full voter turnout as have drawn the conclusion that the Conservative Party would win the election if they encourage more eligible voters to vote. Such findings re-analyse the outcome of the 2019 election and give possible strategies to the Federal parities on their next election so that it will affect the method of canvass in the future. 

## Key Words

 Simulate; Full voter turnout; 2019 Election; Liberal; Conservative; Multilevel Regression with Post-stratification
 
 
# Introduction

Canadian General Election is an election that elects the Member of Parliament(MP) in which each eligible voters vote for their preferred candidate in thee riding that they belong to. Unlike other democratic system in the world, Canada adopted the Westminster System that is unlike the United States. Voters in Canada do not vote for the Prime Minister, instead they vote for the MP and the MPs from the winning party will decide who is going to be the Prime Minister. 

In the 2019 election, Liberal Party won the majority of seats in the Parliament but only formed a minority government and the difference between the Liberals and the second largest party---- Conservative Party is very slim. As a left wing party, Liberals gain most of their supports from the city, elites with high incomes, racial minorities and etc. While the Conservatives acquires most of their votes from countryside, middle class and mainly white people according to the Canada General Social Survey. However, most of the election analysis or predictions have only focused on the data of the registered voters but neglected the eligible voters who did not vote in the election. In the 2019 election, Conservative Party has won 1.2% more popular vote than the Liberals but still lost the election to the Liberals with a total voter turnout of 67%. As the difference between those two parties are getting closer, and the world’s general attitude towards politics is getting more acute and people with different ideologies are getting more hardly to recognize each other based on the example of the 2020 United States Presidential Election in which both Donald Trump and Joe Biden have received historical highest popular votes in the election. It is not hard to see that it is absolutely possible for Canadian Federal parties to motivate more citizens to vote in the next election and the power of those potential voters is big enough to overturn the small difference between two parties. Hence, the key point of my research is mainly focusing on the people who did not vote which constitute 33% of the total population. 

In the research, R Core Team is used to create model codes and Data cleaning. I have used the data from Current Employment Statistics (CES) and Canadian General Social Survey(GSS) which includes region, income level, racial status, gender and voting status from the survey by using MRP model. And I will be mainly use the data from the voters who checked “not to vote” in the survey. Based on the information that those respondents have provided, it can be concluded that eligible voters who did not vote match more characteristics of Conservative voters hence after the analysis, we can draw the conclusion that if the Conservative Party could have motivated more voters to vote, it is possible for them to overturn the result. 

Although the research can reflect certain characters of passive voters, we will still encounter bias and systematic errors. As the surveys have limited resources of the sentiment of voters who chose not to vote. Some people may be totally careless about the result of the election, and others may have a strong determination of not voting. Weaknesses will be further discussed in the following discussion session. 

In conclusion, this research is using the data from 2019 election and the purpose of this research is to analyse the eligible voters who did not vote in order to give the parties more instruction to modify their strategies. There may be some systematic errors that make the result harder to predict. But I do hope this model can better reflect the potential voting behaviour and indirectly predict the next election with higher voter turnout. 

# Data

# Model

# Results

# Discussion

# References






